chore: try and fix script

diff --git a/.github/workflows/pzl-scraper.yml b/.github/workflows/pzl-scraper.yml
--- a/.github/workflows/pzl-scraper.yml
+++ b/.github/workflows/pzl-scraper.yml
@@ -22,11 +22,11 @@ jobs:
       - name: Install System Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y libxml2-dev libxslt-dev
+          sudo apt-get install -y libxml2-dev libxslt-dev jq
 
-      - name: Install Dependencies
+      - name: Install Python Dependencies
         run: |
-          pip install xword-dl
+          pip install xword-dl requests
 
       - name: Download Puzzle
         continue-on-error: true
@@ -45,12 +45,16 @@ jobs:
       - name: Upload puzzle to Dropbox
         run: |
           DATE=$(date +'%Y%m%d_%A')
-          response=$(curl https://api.dropbox.com/oauth2/token \
+          response=$(curl -s https://api.dropbox.com/oauth2/token \
             -d grant_type=refresh_token \
             -d refresh_token=${{ secrets.REFRESH_TOKEN }} \
             --data-urlencode "client_id=${{ secrets.APP_KEY }}" \
             --data-urlencode "client_secret=${{ secrets.APP_SECRET }}")
           access_token=$(echo $response | jq -r '.access_token')
+          if [[ -z "$access_token" ]]; then
+            echo "Failed to get access token"
+            exit 1
+          fi
           echo "NEW_DROPBOX_ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
 
           declare -A puzzles
